[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "python-dotenvx"
dynamic = ["version"]
description = "a secure dotenv–from the creator of `dotenv`"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
license = { text = "BSD-3-Clause" }
authors = [
  { name = "dotenv", email = "mot@dotenvx.com" }
]
keywords = [
  "environment",
  "environment variables",
  "env",
  "dotenv",
  "python",
  "dotenvx"
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Rust",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://dotenvx.com"
Repository = "https://github.com/dotenvx/python-dotenvx"

[tool.maturin]
python-source = "src"
module-name = "dotenvx._native"
features = ["pyo3/extension-module"]
