__title__ = "python-dotenvx"
__description__ = "a secure dotenv–from the creator of `dotenv`"
__url__ = "https://github.com/dotenvx/python-dotenvx"
__version__ = "2.0.0"
__author__ = "dotenv"
__author_email__ = "mot@dotenvx.com"
__license__ = "BSD-3-Clause"
